Maybe metadata works now?

diff --git a/.github/workflows/reusable-build.yml b/.github/workflows/reusable-build.yml
--- a/.github/workflows/reusable-build.yml
+++ b/.github/workflows/reusable-build.yml
@@ -117,11 +117,38 @@ jobs:
           # - "-minimal"
           # - ""
           - "-hci"
+        include: &include
+          # - image_suffix: "-minimal"
+          #   description: An OCI image of Fedora CoreOS with a few extra tools and suitable for running in a VM
+          # - image_suffix: ""
+          #   description: An OCI image of Fedora CoreOS with a few extra tools, hardware support, and storage utilities
+          - image_suffix: "-hci"
+            description: A hyper-converged infrastructure OCI image of Fedora CoreOS (storage + hypervisor)
         architecture: ${{ fromJson(inputs.architecture) }}
 
     steps:
       - name: Checkout Push to Registry action
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
+
+      - name: Update Buildah
+        shell: bash
+        run: &buildah |
+          set -euxo pipefail
+
+          case "$(uname -m)" in
+            x86_64)
+              IMAGE_ARCH='amd64'
+              ;;
+            aarch64)
+              IMAGE_ARCH='arm64'
+              ;;
+            *)
+              printf "Invalid architecture" >&2
+              exit 1
+              ;;
+          esac
+
+          curl -L# "https://github.com/HeavenVolkoff/buildah-static/releases/latest/download/buildah-${IMAGE_ARCH}.tar.gz" | sudo tar -xzf - -C /usr/local/bin
 
       - name: Download stream info artifact
         uses: &download actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
@@ -133,7 +160,7 @@ jobs:
       - name: Matrix variables
         shell: bash
         run: |
-          set -x
+          set -euxo pipefail
           IMAGE_NAME='ucore${{ matrix.image_suffix }}'
           echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
           cat stream-info.env >> $GITHUB_ENV
@@ -178,6 +205,20 @@ jobs:
               echo "pulled akmods-zfs image kernel ($kernel) does not match expected kernel (${{ env.KERNEL_VERSION }})"
               exit 1
           fi
+
+      # Build metadata
+      - name: Image Metadata
+        uses: &metadata_action docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
+        id: meta
+        with: &metadata
+          images: |
+            ${{ env.IMAGE_NAME }}
+          labels: |
+            io.artifacthub.package.logo-url=https://avatars.githubusercontent.com/u/120078124?s=200&v=4
+            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/ublue-os/ucore/main/README.md
+            org.opencontainers.image.description=${{ matrix.description }}
+            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
+            org.opencontainers.image.version=${{ env.IMAGE_VERSION }}
 
       # Build image using Buildah action
       - name: Build Image
@@ -244,14 +285,12 @@ jobs:
       fail-fast: false
       matrix:
         image_suffix: *image_suffix
-        include:
-          # - image_suffix: "-minimal"
-          #   description: An OCI image of Fedora CoreOS with a few extra tools and suitable for running in a VM
-          # - image_suffix: ""
-          #   description: An OCI image of Fedora CoreOS with a few extra tools, hardware support, and storage utilities
-          - image_suffix: "-hci"
-            description: A hyper-converged infrastructure OCI image of Fedora CoreOS (storage + hypervisor)
+        include: *include
     steps:
+      - name: Update Buildah
+        shell: bash
+        run: *buildah
+
       - name: Download stream info artifact
         uses: *download
         with:
@@ -277,17 +316,9 @@ jobs:
 
       # Build metadata
       - name: Image Metadata
-        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
+        uses: *metadata_action
         id: meta
-        with:
-          images: |
-            ${{ env.IMAGE_NAME }}
-          labels: |
-            io.artifacthub.package.logo-url=https://avatars.githubusercontent.com/u/120078124?s=200&v=4
-            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/ublue-os/ucore/main/README.md
-            org.opencontainers.image.description=${{ matrix.description }}
-            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
-            org.opencontainers.image.version=${{ env.IMAGE_VERSION }}
+        with: *metadata
 
       - name: Create Manifest
         id: create_manifest
@@ -307,7 +338,7 @@ jobs:
           done
 
           echo "Creating manifest for $IMAGE_NAME"
-          buildah manifest create --annotation='${{ steps.meta.outputs.annotations }}' "${IMAGE_NAME}:latest"
+          buildah manifest create --annotation="$(echo '${{ steps.meta.outputs.annotations }}' | awk -F':' '{ print $2 }' | head -c -1 | tr '\n' ',')" "${IMAGE_NAME}:latest"
 
           for IMAGE_TAG in "${IMAGE_TAGS[@]}"; do
             IMAGE="${IMAGE_NAME}:${IMAGE_TAG}"
