idk

diff --git a/.github/workflows/reusable-build.yml b/.github/workflows/reusable-build.yml
--- a/.github/workflows/reusable-build.yml
+++ b/.github/workflows/reusable-build.yml
@@ -130,47 +130,6 @@ jobs:
       - name: Checkout Push to Registry action
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
 
-      - name: Update Podman and Buildah
-        shell: bash
-        run: &buildah |
-          set -euxo pipefail
-
-          case "$(uname -m)" in
-            x86_64)
-              IMAGE_ARCH='amd64'
-              ;;
-            aarch64)
-              IMAGE_ARCH='arm64'
-              ;;
-            *)
-              printf "Invalid architecture" >&2
-              exit 1
-              ;;
-          esac
-
-          # Remove snap
-          sudo apt remove -yq --purge firefox
-          while [ -n "$(snap list | awk '!/^Name/ {print $1}')" ]
-          do
-              SNAPS=( $(snap list | awk '!/^Name/ {print $1}') )
-              for s in "${SNAPS[@]}"
-              do
-                  sudo snap disable "$s"
-                  sudo snap remove --purge "$s"
-              done
-          done;
-
-          sudo rm -rf /etc/systemd/system/snapd.mounts.target.wants
-
-          sudo apt-get remove -yq --purge snapd buildah crun podman fuse3 fuse-overlayfs passt
-
-          sudo rm -rf /var/cache/snapd/ /var/snap/
-
-          curl -fsSL# "https://github.com/mgoltzsche/podman-static/releases/latest/download/podman-linux-${IMAGE_ARCH}.tar.gz" | sudo tar --strip-component 1 -xzf - -C /
-          curl -fsSL# "https://github.com/HeavenVolkoff/buildah-static/releases/latest/download/buildah-${IMAGE_ARCH}.tar.gz" | sudo tar -xzf - -C /usr/local/bin
-          sudo sed -Ei 's!^profile podman /usr/bin/podman !profile podman /usr/{bin,local/bin}/podman !' /etc/apparmor.d/podman
-          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
-
       - name: Download stream info artifact
         uses: &download actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
         with:
@@ -274,7 +233,9 @@ jobs:
           IMAGE_TAG='${{ matrix.architecture }}'
           IMAGE_NAME='${{ env.IMAGE_NAME }}'
 
-          podman run --rm --entrypoint cat "${IMAGE_NAME}:${IMAGE_TAG}" /usr/lib/modules/${{ env.KERNEL_VERSION }}/vmlinuz > ./vmlinuz
+          podman create --name "${IMAGE_NAME}-${IMAGE_TAG}" "${IMAGE_NAME}:${IMAGE_TAG}" 
+          podman cp "${IMAGE_NAME}-${IMAGE_TAG}":/usr/lib/modules/${{ env.KERNEL_VERSION }}/vmlinuz .
+          podman rm "${IMAGE_NAME}-${IMAGE_TAG}"
           sbverify --list vmlinuz
           curl --retry 3 -Lo kernel-sign.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key.der
           curl --retry 3 -Lo akmods.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key_2.der
@@ -308,7 +269,44 @@ jobs:
     steps:
       - name: Update Podman and Buildah
         shell: bash
-        run: *buildah
+        run: &buildah |
+          set -euxo pipefail
+
+          case "$(uname -m)" in
+            x86_64)
+              IMAGE_ARCH='amd64'
+              ;;
+            aarch64)
+              IMAGE_ARCH='arm64'
+              ;;
+            *)
+              printf "Invalid architecture" >&2
+              exit 1
+              ;;
+          esac
+
+          # Remove snap
+          sudo apt remove -yq --purge firefox
+          while [ -n "$(snap list | awk '!/^Name/ {print $1}')" ]
+          do
+              SNAPS=( $(snap list | awk '!/^Name/ {print $1}') )
+              for s in "${SNAPS[@]}"
+              do
+                  sudo snap disable "$s"
+                  sudo snap remove --purge "$s"
+              done
+          done;
+
+          sudo rm -rf /etc/systemd/system/snapd.mounts.target.wants
+
+          sudo apt-get remove -yq --purge snapd buildah crun podman fuse3 fuse-overlayfs passt
+
+          sudo rm -rf /var/cache/snapd/ /var/snap/
+
+          curl -fsSL# "https://github.com/mgoltzsche/podman-static/releases/latest/download/podman-linux-${IMAGE_ARCH}.tar.gz" | sudo tar --strip-component 1 -xzf - -C /
+          curl -fsSL# "https://github.com/HeavenVolkoff/buildah-static/releases/latest/download/buildah-${IMAGE_ARCH}.tar.gz" | sudo tar -xzf - -C /usr/local/bin
+          sudo sed -Ei 's!^profile podman /usr/bin/podman !profile podman /usr/{bin,local/bin}/podman !' /etc/apparmor.d/podman
+          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
 
       - name: Download stream info artifact
         uses: *download
